spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
            allowedMethods: 
              - "*"
            allowedHeaders: 
              - "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
        - id: activity-service
          uri: lb://ACTIVITYSERVICE
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: lb://AISERVICES
          predicates:
            - Path=/api/recommendations/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/master
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
